const { chromium } = require('playwright-core');
const path = require('path');
const APP_URL = process.env.APP_URL || 'file://' + path.resolve(__dirname, '..', 'index.html');
const launchOpts = { args: ['--no-sandbox'] };
if (process.env.CHROMIUM_PATH) launchOpts.executablePath = process.env.CHROMIUM_PATH;
(async () => {
  const b = await chromium.launch(launchOpts);
  const pg = await b.newPage({ viewport: { width: 390, height: 844 } });
  const errs = []; pg.on('pageerror', e => errs.push(e.message));
  const assert = (c, m) => { if (!c) throw new Error('FAIL: ' + m); console.log('ok:', m); };
  const vis = sel => pg.$eval(sel, e => getComputedStyle(e).display !== 'none');
  await pg.goto(APP_URL);
  assert((await pg.$$('.home-hero')).length === 0, 'hero removed from home');
  assert(await pg.$eval('#infoBtn', e => e.closest('.logo-text') !== null && getComputedStyle(e).borderStyle === 'none'), 'ⓘ next to title, no ring');
  assert(!(await vis('#infoPop')), 'popover hidden by default');
  await pg.click('#infoBtn');
  assert(await vis('#infoPop') && (await pg.$eval('#infoPop', e => e.textContent)).includes('408 official-style questions'), 'click shows tooltip with hero text');
  assert((await pg.$$eval('#infoPop .hero-badge', els => els.length)) === 3, 'three badges in tooltip');
  assert(await pg.$eval('#infoBtn', e => e.getAttribute('aria-expanded') === 'true'), 'aria-expanded true');
  const box = await pg.$eval('#infoPop', e => e.getBoundingClientRect());
  assert(box.right <= 390 && box.left >= 0, 'popover fits viewport width');
  await pg.screenshot({ path: 'shot-info.png' });
  await pg.click('#infoBtn');
  assert(!(await vis('#infoPop')), 'second click hides');
  await pg.click('#infoBtn');
  await pg.click('#infoPop h2');
  assert(await vis('#infoPop'), 'click inside keeps it open');
  await pg.mouse.click(30, 760);
  assert(!(await vis('#infoPop')), 'click outside closes');
  await pg.click('#infoBtn'); await pg.keyboard.press('Escape');
  assert(!(await vis('#infoPop')), 'Escape closes');
  // still works on quiz screen with stats visible
  await pg.evaluate(() => { pendingMode = 'practice'; startExam(1); });
  await pg.click('#infoBtn');
  assert(await vis('#infoPop') && await vis('#headerStats'), 'works on quiz screen alongside stats');
  assert(errs.length === 0, 'no page errors: ' + errs.join(';'));
  await b.close(); console.log('INFO PASS');
})().catch(e => { console.error(e.message); process.exit(1); });
